#!/bin/sh
#
# A simple shell script to make RPMs from a CVS directory
# NB: make sure cvs2cl will work, and that your user has
# write permissions on RPM's build directory.
#
# $Id: make-rpm,v 1.1 2004/02/17 14:23:04 jodrell Exp $

CWD=$PWD
VERSION=$1
TOPDIR=$HOME/rpmbuild
DIR=`basename $PWD`

echo Creating temporary copy of package:
rm -rf /tmp/$DIR-$VERSION
cp -Rp --no-dereference $PWD /tmp/$DIR-$VERSION
pushd /tmp/$DIR-$VERSION

echo Generating ChangeLog:
cvs2cl

echo Stripping CVS files:
find -print | grep CVS | xargs rm -rf

echo Creating tarball:
pushd ..
tar zcf $DIR-$VERSION.tar.gz $DIR-$VERSION/
rm -rf $DIR-$VERSION/

mv $DIR-$VERSION.tar.gz $CWD/

cd $CWD

echo Building Source RPM:
rpmbuild -ta $DIR-$VERSION.tar.gz
mv $TOPDIR/SRPMS/$DIR-$VERSION*src.rpm ./

echo Building NoArch RPM:
rpmbuild -tb $DIR-$VERSION.tar.gz --target=noarch
mv $TOPDIR/RPMS/noarch/$DIR-$VERSION*.rpm ./
