#!/bin/sh
#
# A simple shell script to make RPMs from a CVS directory
# NB: make sure cvs2cl will work, and that your user has
# write permissions on RPM's build directory.
#
# $Id: make-rpm,v 1.7 2004/04/05 20:16:31 jodrell Exp $

CWD=$PWD
VERSION=$1
TOPDIR=$HOME/.rpmbuild
DIR=`basename $PWD`

if [ -z $VERSION ] ; then
	echo Usage: $0 [VERSION]
	exit
fi

echo Creating temporary copy of package:
rm -rf /tmp/$DIR-$VERSION
cp -Rp --no-dereference $PWD /tmp/$DIR-$VERSION
cd /tmp/$DIR-$VERSION

echo Fixing permissions on pixmaps:
find share/ -name '*png' -exec chmod 644 \{\} \;

echo Stripping CVS files:
find -print | grep CVS | xargs rm -rf

echo Creating tarball:
cd ..
tar zcf $DIR-$VERSION.tar.gz $DIR-$VERSION/
rm -rf $DIR-$VERSION/

mv $DIR-$VERSION.tar.gz $HOME/

cd $CWD

echo Building Source RPM:
rpmbuild --quiet -ta $HOME/$DIR-$VERSION.tar.gz 1> /dev/null 2> /dev/null
mv $TOPDIR/SRPMS/$DIR-$VERSION*src.rpm $HOME/

echo Building NoArch RPM:
rpmbuild --quiet -tb $HOME/$DIR-$VERSION.tar.gz --target=noarch 1> /dev/null 2> /dev/null
mv $TOPDIR/RPMS/noarch/$DIR-$VERSION*.rpm $HOME/
