#!/usr/bin/perl
# $Id: perlpanel,v 1.1 2003/05/27 14:54:42 jodrell Exp $
use lib 'lib/';
use PerlPanel;
use strict;

push(@PerlPanel::APPLETSDIR, 'lib/PerlPanel/Applet');

my $panel = PerlPanel->new;
$panel->init;

exit;
