#!/usr/bin/perl
# perlpanel-run-command - a command dialog.
# This file is part of PerlPanel.
# 
# PerlPanel is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# PerlPanel is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PerlPanel; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id: perlpanel-run-dialog,v 1.3 2004/02/02 12:02:45 jodrell Exp $

use strict;

use lib (-e '@LIBDIR@' ? '@LIBDIR@' : $ENV{PWD}.'/lib/'); 

$PerlPanel::PREFIX = (-e '@PREFIX@' ? '@PREFIX@' : $ENV{PWD});

$ENV{PATH} = $ENV{PATH}.':'.$ENV{PWD}.'/src' if (!-e '@PREFIX@');

my $PREFIX = (-e '@PREFIX' ? '@PREFIX@' : $ENV{PWD});

use Gtk2 -init;
use PerlPanel;

require("$PREFIX/lib/PerlPanel/Applet/Commander.pm");

$PerlPanel::Applet::Commander::iconfile = sprintf('%s/share/pixmaps/perlpanel/applets/commander.png', $PREFIX);

PerlPanel::Applet::Commander->run;
