#!/usr/bin/perl
# $Id: perlpanel,v 1.2 2003/06/05 23:25:53 jodrell Exp $
use lib (-e '@LIBDIR@' ? '@LIBDIR@' : $ENV{PWD}.'/lib/');
use PerlPanel;

# if you're running from a sandbox, you can get PerlPanel to run by symlinking
# this file into a directory in your PATH, and symlinking the
# lib/PerlPanel/Applet to ~/.perlpanel/applets. Then you can work on PerlPanel
# without having to install it, or hard-coding paths into the scripts.

$PerlPanel::PREFIX = (-e '@PREFIX@' ? '@PREFIX@' : $PerlPanel::PREFIX);

my $panel = PerlPanel->new;

$panel->init;

exit;
